import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "./context/cartcontext";
import LayoutWrapper from "@/components/Layoutwrapper";
import { Suspense } from "react";
import { Toaster } from "sonner";

// ✅ ADD THIS
import { GoogleOAuthProvider } from "@react-oauth/google";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* 🔥 GOOGLE PROVIDER */}
        <GoogleOAuthProvider
          clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID!}
        >
          <CartProvider>
            <Suspense fallback={<div>Loading...</div>}>
              <LayoutWrapper>{children}</LayoutWrapper>
            </Suspense>
          <Toaster position="top-right" richColors closeButton duration={3000} />
          </CartProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
